#!/usr/bin/env bash

if [[ -f ./.env ]]; then
  # shellcheck disable=SC1091
  source ./.env
fi

go build -o ./aws-s3

./aws-s3 prune -bucket "${BUCKET:?}" -region "${REGION:?}" -prefix "${PATH_PREFIX:-}hourly/" -max-age 24h -progress -dry-run
./aws-s3 prune -bucket "${BUCKET:?}" -region "${REGION:?}" -prefix "${PATH_PREFIX:-}daily/" -max-age 168h -progress -dry-run
./aws-s3 prune -bucket "${BUCKET:?}" -region "${REGION:?}" -prefix "${PATH_PREFIX:-}weekly/" -max-age 744h -progress -dry-run
./aws-s3 prune -bucket "${BUCKET:?}" -region "${REGION:?}" -prefix "${PATH_PREFIX:-}monthly/" -max-age 8928h -progress -dry-run
